from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGridLayout, QHBoxLayout,
    QLabel, QPushButton, QSizePolicy, QVBoxLayout,
    QWidget)
class Ui_ToneMakesure(object):
    def setupUi(self, ToneMakesure):
        if not ToneMakesure.objectName():
            ToneMakesure.setObjectName(u"ToneMakesure")
        ToneMakesure.resize(261, 210)
        self.gridLayout = QGridLayout(ToneMakesure)
        self.gridLayout.setObjectName(u"gridLayout")
        self.SmartTone = QLabel(ToneMakesure)
        self.SmartTone.setObjectName(u"SmartTone")
        self.SmartTone.setMaximumSize(QSize(16777215, 50))
        font = QFont()
        font.setPointSize(20)
        self.SmartTone.setFont(font)
        self.SmartTone.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)
        self.gridLayout.addWidget(self.SmartTone, 0, 0, 1, 1)
        self.label = QLabel(ToneMakesure)
        self.label.setObjectName(u"label")
        self.label.setMaximumSize(QSize(16777215, 20))
        font1 = QFont()
        font1.setPointSize(15)
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.NewTone = QLabel(ToneMakesure)
        self.NewTone.setObjectName(u"NewTone")
        self.NewTone.setFont(font)
        self.NewTone.setAlignment(Qt.AlignCenter)
        self.verticalLayout.addWidget(self.NewTone)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.widget_2 = QWidget(ToneMakesure)
        self.widget_2.setObjectName(u"widget_2")
        self.horizontalLayout.addWidget(self.widget_2)
        self.ChooseTone = QComboBox(ToneMakesure)
        self.ChooseTone.addItem("")
        self.ChooseTone.addItem("")
        self.ChooseTone.addItem("")
        self.ChooseTone.addItem("")
        self.ChooseTone.addItem("")
        self.ChooseTone.addItem("")
        self.ChooseTone.addItem("")
        self.ChooseTone.addItem("")
        self.ChooseTone.addItem("")
        self.ChooseTone.addItem("")
        self.ChooseTone.addItem("")
        self.ChooseTone.addItem("")
        self.ChooseTone.setObjectName(u"ChooseTone")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChooseTone.sizePolicy().hasHeightForWidth())
        self.ChooseTone.setSizePolicy(sizePolicy)
        self.ChooseTone.setMinimumSize(QSize(95, 50))
        self.ChooseTone.setMaximumSize(QSize(1000, 16777215))
        self.ChooseTone.setFont(font)
        self.ChooseTone.setIconSize(QSize(30, 30))
        self.ChooseTone.setDuplicatesEnabled(False)
        self.horizontalLayout.addWidget(self.ChooseTone)
        self.widget = QWidget(ToneMakesure)
        self.widget.setObjectName(u"widget")
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.ToneBtn = QPushButton(ToneMakesure)
        self.ToneBtn.setObjectName(u"ToneBtn")
        self.gridLayout.addWidget(self.ToneBtn, 3, 0, 1, 1)
        self.retranslateUi(ToneMakesure)
        QMetaObject.connectSlotsByName(ToneMakesure)
    def retranslateUi(self, ToneMakesure):
        ToneMakesure.setWindowTitle(QCoreApplication.translate("ToneMakesure", u"\u8c03\u6027\u786e\u8ba4", None))
        self.SmartTone.setText(QCoreApplication.translate("ToneMakesure", u"\u6b64\u97f3\u4e50\u7684\u8c03\u6027\u8bc6\u522b\u4e3a", None))
        self.label.setText(QCoreApplication.translate("ToneMakesure", u"\u82e5\u8bc6\u522b\u9519\u8bef\u60a8\u53ef\u4ee5", None))
        self.NewTone.setText(QCoreApplication.translate("ToneMakesure", u"\u66f4\u6539\u8c03\u6027\u4e3a", None))
        self.ChooseTone.setItemText(0, QCoreApplication.translate("ToneMakesure", u"C", None))
        self.ChooseTone.setItemText(1, QCoreApplication.translate("ToneMakesure", u"C#", None))
        self.ChooseTone.setItemText(2, QCoreApplication.translate("ToneMakesure", u"D", None))
        self.ChooseTone.setItemText(3, QCoreApplication.translate("ToneMakesure", u"D#", None))
        self.ChooseTone.setItemText(4, QCoreApplication.translate("ToneMakesure", u"E", None))
        self.ChooseTone.setItemText(5, QCoreApplication.translate("ToneMakesure", u"F", None))
        self.ChooseTone.setItemText(6, QCoreApplication.translate("ToneMakesure", u"F#", None))
        self.ChooseTone.setItemText(7, QCoreApplication.translate("ToneMakesure", u"G", None))
        self.ChooseTone.setItemText(8, QCoreApplication.translate("ToneMakesure", u"G#", None))
        self.ChooseTone.setItemText(9, QCoreApplication.translate("ToneMakesure", u"A", None))
        self.ChooseTone.setItemText(10, QCoreApplication.translate("ToneMakesure", u"A#", None))
        self.ChooseTone.setItemText(11, QCoreApplication.translate("ToneMakesure", u"B", None))
        self.ToneBtn.setText(QCoreApplication.translate("ToneMakesure", u"\u786e\u5b9a", None))