from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QPushButton, QSizePolicy,
    QWidget)
class Ui_themeguide(object):
    def setupUi(self, themeguide):
        if not themeguide.objectName():
            themeguide.setObjectName(u"themeguide")
        themeguide.resize(400, 300)
        self.gridLayout = QGridLayout(themeguide)
        self.gridLayout.setObjectName(u"gridLayout")
        self.Lblue_btn = QPushButton(themeguide)
        self.Lblue_btn.setObjectName(u"Lblue_btn")
        self.Lblue_btn.setMinimumSize(QSize(0, 50))
        self.gridLayout.addWidget(self.Lblue_btn, 0, 0, 1, 1)
        self.Lred_btn = QPushButton(themeguide)
        self.Lred_btn.setObjectName(u"Lred_btn")
        self.Lred_btn.setMinimumSize(QSize(0, 50))
        self.gridLayout.addWidget(self.Lred_btn, 0, 1, 1, 1)
        self.Lpink_btn = QPushButton(themeguide)
        self.Lpink_btn.setObjectName(u"Lpink_btn")
        self.Lpink_btn.setMinimumSize(QSize(0, 50))
        self.gridLayout.addWidget(self.Lpink_btn, 1, 0, 1, 1)
        self.Lpurple_btn = QPushButton(themeguide)
        self.Lpurple_btn.setObjectName(u"Lpurple_btn")
        self.Lpurple_btn.setMinimumSize(QSize(0, 50))
        self.gridLayout.addWidget(self.Lpurple_btn, 1, 1, 1, 1)
        self.Dblue_btn = QPushButton(themeguide)
        self.Dblue_btn.setObjectName(u"Dblue_btn")
        self.Dblue_btn.setMinimumSize(QSize(0, 50))
        self.gridLayout.addWidget(self.Dblue_btn, 2, 0, 1, 1)
        self.Dred_btn = QPushButton(themeguide)
        self.Dred_btn.setObjectName(u"Dred_btn")
        self.Dred_btn.setMinimumSize(QSize(0, 50))
        self.gridLayout.addWidget(self.Dred_btn, 2, 1, 1, 1)
        self.Dpink_btn = QPushButton(themeguide)
        self.Dpink_btn.setObjectName(u"Dpink_btn")
        self.Dpink_btn.setMinimumSize(QSize(0, 50))
        self.gridLayout.addWidget(self.Dpink_btn, 3, 0, 1, 1)
        self.Dpurple_btn = QPushButton(themeguide)
        self.Dpurple_btn.setObjectName(u"Dpurple_btn")
        self.Dpurple_btn.setMinimumSize(QSize(0, 50))
        self.gridLayout.addWidget(self.Dpurple_btn, 3, 1, 1, 1)
        self.retranslateUi(themeguide)
        QMetaObject.connectSlotsByName(themeguide)
    def retranslateUi(self, themeguide):
        themeguide.setWindowTitle(QCoreApplication.translate("themeguide", u"\u4e3b\u9898\u83dc\u5355", None))
        self.Lblue_btn.setText(QCoreApplication.translate("themeguide", u"\u4eae\u84dd\u8272\u4e3b\u9898", None))
        self.Lred_btn.setText(QCoreApplication.translate("themeguide", u"\u4eae\u7ea2\u8272\u4e3b\u9898", None))
        self.Lpink_btn.setText(QCoreApplication.translate("themeguide", u"\u4eae\u7c89\u8272\u4e3b\u9898", None))
        self.Lpurple_btn.setText(QCoreApplication.translate("themeguide", u"\u4eae\u7d2b\u8272\u4e3b\u9898", None))
        self.Dblue_btn.setText(QCoreApplication.translate("themeguide", u"\u9ed1\u84dd\u8272\u4e3b\u9898", None))
        self.Dred_btn.setText(QCoreApplication.translate("themeguide", u"\u9ed1\u7ea2\u8272\u4e3b\u9898", None))
        self.Dpink_btn.setText(QCoreApplication.translate("themeguide", u"\u9ed1\u7c89\u8272\u4e3b\u9898", None))
        self.Dpurple_btn.setText(QCoreApplication.translate("themeguide", u"\u9ed1\u7d2b\u8272\u4e3b\u9898", None))