from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QHBoxLayout, QLabel,
    QPushButton, QSizePolicy, QWidget)
class Ui_audioSPForm(object):
    def setupUi(self, audioSPForm):
        if not audioSPForm.objectName():
            audioSPForm.setObjectName(u"audioSPForm")
        audioSPForm.resize(498, 296)
        self.gridLayout = QGridLayout(audioSPForm)
        self.gridLayout.setObjectName(u"gridLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.openvolacebtn = QPushButton(audioSPForm)
        self.openvolacebtn.setObjectName(u"openvolacebtn")
        self.openvolacebtn.setEnabled(False)
        self.openvolacebtn.setMinimumSize(QSize(115, 0))
        self.openvolacebtn.setMaximumSize(QSize(90, 16777215))
        self.horizontalLayout.addWidget(self.openvolacebtn)
        self.openDrambtn = QPushButton(audioSPForm)
        self.openDrambtn.setObjectName(u"openDrambtn")
        self.openDrambtn.setEnabled(False)
        self.openDrambtn.setMinimumSize(QSize(115, 0))
        self.openDrambtn.setMaximumSize(QSize(90, 16777215))
        self.horizontalLayout.addWidget(self.openDrambtn)
        self.openBassbtn = QPushButton(audioSPForm)
        self.openBassbtn.setObjectName(u"openBassbtn")
        self.openBassbtn.setEnabled(False)
        self.openBassbtn.setMinimumSize(QSize(115, 0))
        self.openBassbtn.setMaximumSize(QSize(90, 16777215))
        self.horizontalLayout.addWidget(self.openBassbtn)
        self.openPianobtn = QPushButton(audioSPForm)
        self.openPianobtn.setObjectName(u"openPianobtn")
        self.openPianobtn.setEnabled(False)
        self.openPianobtn.setMinimumSize(QSize(115, 0))
        self.openPianobtn.setMaximumSize(QSize(90, 16777215))
        self.horizontalLayout.addWidget(self.openPianobtn)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.label = QLabel(audioSPForm)
        self.label.setObjectName(u"label")
        font = QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.widget_2 = QWidget(audioSPForm)
        self.widget_2.setObjectName(u"widget_2")
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget = QWidget(audioSPForm)
        self.widget.setObjectName(u"widget")
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.savevolacsbtn = QPushButton(audioSPForm)
        self.savevolacsbtn.setObjectName(u"savevolacsbtn")
        self.savevolacsbtn.setEnabled(False)
        self.savevolacsbtn.setMinimumSize(QSize(115, 0))
        self.savevolacsbtn.setMaximumSize(QSize(90, 16777215))
        self.horizontalLayout_2.addWidget(self.savevolacsbtn)
        self.saveDrambtn = QPushButton(audioSPForm)
        self.saveDrambtn.setObjectName(u"saveDrambtn")
        self.saveDrambtn.setEnabled(False)
        self.saveDrambtn.setMinimumSize(QSize(115, 0))
        self.saveDrambtn.setMaximumSize(QSize(90, 16777215))
        self.horizontalLayout_2.addWidget(self.saveDrambtn)
        self.saveBassbtn = QPushButton(audioSPForm)
        self.saveBassbtn.setObjectName(u"saveBassbtn")
        self.saveBassbtn.setEnabled(False)
        self.saveBassbtn.setMinimumSize(QSize(115, 0))
        self.saveBassbtn.setMaximumSize(QSize(90, 16777215))
        self.horizontalLayout_2.addWidget(self.saveBassbtn)
        self.savePianobtn = QPushButton(audioSPForm)
        self.savePianobtn.setObjectName(u"savePianobtn")
        self.savePianobtn.setEnabled(False)
        self.savePianobtn.setMinimumSize(QSize(115, 0))
        self.savePianobtn.setMaximumSize(QSize(90, 16777215))
        self.horizontalLayout_2.addWidget(self.savePianobtn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 0, 1, 1)
        self.choosemusicbtn = QPushButton(audioSPForm)
        self.choosemusicbtn.setObjectName(u"choosemusicbtn")
        self.gridLayout.addWidget(self.choosemusicbtn, 3, 0, 1, 1)
        self.loadinglab = QLabel(audioSPForm)
        self.loadinglab.setObjectName(u"loadinglab")
        self.loadinglab.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.loadinglab, 4, 0, 1, 1)
        self.retranslateUi(audioSPForm)
        QMetaObject.connectSlotsByName(audioSPForm)
    def retranslateUi(self, audioSPForm):
        audioSPForm.setWindowTitle(QCoreApplication.translate("audioSPForm", u"\u591a\u97f3\u9891\u5206\u79bb", None))
        self.openvolacebtn.setText(QCoreApplication.translate("audioSPForm", u"\u6253\u5f00\u4eba\u58f0\u97f3\u9891", None))
        self.openDrambtn.setText(QCoreApplication.translate("audioSPForm", u"\u6253\u5f00\u9f13\u97f3\u9891", None))
        self.openBassbtn.setText(QCoreApplication.translate("audioSPForm", u"\u6253\u5f00\u8d1d\u65af\u97f3\u9891", None))
        self.openPianobtn.setText(QCoreApplication.translate("audioSPForm", u"\u6253\u5f00\u94a2\u7434\u97f3\u9891", None))
        self.label.setText(QCoreApplication.translate("audioSPForm", u"\u4e50\u5668\u97f3\u9891\u5206\u79bb\u5de5\u5177\n"
"\u5206\u79bb\u6b4c\u66f2\u7684\u4eba\u58f0\u3001\u8d1d\u65af\u3001\u9f13\u3001\u94a2\u7434", None))
        self.savevolacsbtn.setText(QCoreApplication.translate("audioSPForm", u"\u4fdd\u5b58\u4eba\u58f0\u97f3\u9891", None))
        self.saveDrambtn.setText(QCoreApplication.translate("audioSPForm", u"\u4fdd\u5b58\u9f13\u97f3\u9891", None))
        self.saveBassbtn.setText(QCoreApplication.translate("audioSPForm", u"\u4fdd\u5b58\u8d1d\u65af\u97f3\u9891", None))
        self.savePianobtn.setText(QCoreApplication.translate("audioSPForm", u"\u4fdd\u5b58\u94a2\u7434\u97f3\u9891", None))
        self.choosemusicbtn.setText(QCoreApplication.translate("audioSPForm", u"\u9009\u62e9\u97f3\u9891", None))
        self.loadinglab.setText("")